# This will allow users to self assign, and/or drop assignment
[assign]

# Allows @rustbot ready, review, author, or blocked
[shortcut]

[relabel]
allow-unauthenticated = [
    # For Issue areas
    "A-*",
    # Categories
    "C-*",
    # Commands
    "Command-*",
    # Status
    "S-*",
    "regression",
    "Breaking Change",
    "msrv-bump",
]

[autolabel."S-waiting-on-review"]
new_pr = true

[merge-conflicts]
remove = []
add = ["S-waiting-on-author"]
unless = ["S-blocked", "S-waiting-on-review"]

[review-submitted]
reviewed_label = "S-waiting-on-author"
review_labels = ["S-waiting-on-review"]

[review-requested]
remove_labels = ["S-waiting-on-author"]
add_labels = ["S-waiting-on-review"]
