[files]
extend-exclude = [
    "test_book/",
    "*.css",
    "*.svg",
    "*.min.js",
    "tests/",
    "CHANGELOG.md",
    "crates/mdbook-html/front-end/js/highlight.js",
    "crates/mdbook-html/front-end/playground_editor/ace.js",
]
