name: Enhancement
description: Suggest an idea for enhancing mdBook
labels: ["C-enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a 🙋 feature request 😄!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >
        Please provide a clear description of your use case and the problem
        this feature request is trying to solve.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: >
        Please provide a clear and concise description of what you want to happen.
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any additional context or information that might be helpful.
